// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: grpc/protos/watcher.proto

package watcher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatcherServiceClient is the client API for WatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatcherServiceClient interface {
	// PoA to Service
	ImAlive(ctx context.Context, in *AliveInfo, opts ...grpc.CallOption) (*AliveVoid, error)
	// Watcher to Service
	GetAlive(ctx context.Context, in *AliveVoid, opts ...grpc.CallOption) (*AliveInfo, error)
}

type watcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatcherServiceClient(cc grpc.ClientConnInterface) WatcherServiceClient {
	return &watcherServiceClient{cc}
}

func (c *watcherServiceClient) ImAlive(ctx context.Context, in *AliveInfo, opts ...grpc.CallOption) (*AliveVoid, error) {
	out := new(AliveVoid)
	err := c.cc.Invoke(ctx, "/WatcherService/ImAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherServiceClient) GetAlive(ctx context.Context, in *AliveVoid, opts ...grpc.CallOption) (*AliveInfo, error) {
	out := new(AliveInfo)
	err := c.cc.Invoke(ctx, "/WatcherService/GetAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatcherServiceServer is the server API for WatcherService service.
// All implementations must embed UnimplementedWatcherServiceServer
// for forward compatibility
type WatcherServiceServer interface {
	// PoA to Service
	ImAlive(context.Context, *AliveInfo) (*AliveVoid, error)
	// Watcher to Service
	GetAlive(context.Context, *AliveVoid) (*AliveInfo, error)
	mustEmbedUnimplementedWatcherServiceServer()
}

// UnimplementedWatcherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWatcherServiceServer struct {
}

func (UnimplementedWatcherServiceServer) ImAlive(context.Context, *AliveInfo) (*AliveVoid, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImAlive not implemented")
}
func (UnimplementedWatcherServiceServer) GetAlive(context.Context, *AliveVoid) (*AliveInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlive not implemented")
}
func (UnimplementedWatcherServiceServer) mustEmbedUnimplementedWatcherServiceServer() {}

// UnsafeWatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatcherServiceServer will
// result in compilation errors.
type UnsafeWatcherServiceServer interface {
	mustEmbedUnimplementedWatcherServiceServer()
}

func RegisterWatcherServiceServer(s grpc.ServiceRegistrar, srv WatcherServiceServer) {
	s.RegisterService(&WatcherService_ServiceDesc, srv)
}

func _WatcherService_ImAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliveInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).ImAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WatcherService/ImAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).ImAlive(ctx, req.(*AliveInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatcherService_GetAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliveVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).GetAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WatcherService/GetAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).GetAlive(ctx, req.(*AliveVoid))
	}
	return interceptor(ctx, in, info, handler)
}

// WatcherService_ServiceDesc is the grpc.ServiceDesc for WatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WatcherService",
	HandlerType: (*WatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImAlive",
			Handler:    _WatcherService_ImAlive_Handler,
		},
		{
			MethodName: "GetAlive",
			Handler:    _WatcherService_GetAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/protos/watcher.proto",
}
